### PR TITLE
WIP: RiscVDxeIplHandoffOpenSbiLib: Install gEndOfPeiSignalPpi

### PR DESCRIPTION
**Pull request by JohnAZoidberg**
Doesn't work yet, gets stuck like

```
DXE IPL Entry
Loading PEIM D6A2CB7F-6A18-4E2F-B43B-9920A733700A
InvalidateInstructionCacheRange:RISC-V unsupported function.
Loading PEIM at 0x000BFAE5000 EntryPoint=0x000BFAE5240 DxeCore.efi
PROGRESS CODE: V03021001 I0
Loading DXE CORE at 0x000BFAE5000 EntryPoint=0x000BFAE5240
Install PPI: 605EA650-C65C-42E1-BA80-91A52AB618C6
Notify: PPI Guid: 605EA650-C65C-42E1-BA80-91A52AB618C6, Peim notify entry point: 8003B700
DXE Core new stack at BFAC5000, stack pointer at BFAE4FF0
DXE IPL to DXE Core using OpenSBI
          Base address of satck: 0xBFAC5000
          Top address of satck: 0xBFAE4FF0
          HOB list address: 0x8101EA90
          DXE core entry pointer: 0xBFAE5240
          OpenSBI Switch mode arg1: 0x8101EAB8
          OpenSBI Switch mode handler address: 0xBFFD5724
          OpenSBI Switch mode to privilege 0x1
Device Tree can't be expanded to accmodate new node
OpenSBI v0.5
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name          : SiFive Freedom U540
Platform HART Features : RV64ACDFIMSU
Platform Max HARTs     : 5
Current Hart           : 1
Firmware Base          : 0x80000000
Firmware Size          : 704 KB
Runtime SBI Version    : 0.2

PMP0: 0x0000000080000000-0x00000000800fffff (A)
PMP1: 0x0000000000000000-0xffffffffffffffff (A,R,W,X)
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
OpenSBI mode switch DXE IPL Handoff handler entry
```

and continues to loop.

### CODE REVIEW

**Comment by changab** [comment]
ok. What I see is in Install gEndOfPeiSignalPpi(), GetPeiServiceTablePointer() is invoked to get the EFI_PEI_SERVICES from mscrach CSR which is a machine mode CSR. However, RiscVDxeIplHandoffOpenSbiHandler is executed in S-Mode... ><

**Comment by changab** [comment]
Maybe install EndOfPei at the point right before sbi_init().

**Comment by changab** [comment]
Or right before "Setup next address in OpenSBI scratch".

**Comment by JohnAZoidberg** [comment]
> Or right before "Setup next address in OpenSBI scratch".

Yep works!

> ok. What I see is in Install `gEndOfPeiSignalPpi(), GetPeiServiceTablePointer()` is invoked to get the `EFI_PEI_SERVICES` from mscrach CSR which is a machine mode CSR. However, `RiscVDxeIplHandoffOpenSbiHandler` is executed in S-Mode... ><

Should we fail in `GetPeiServicesTablePointer` when we're in S-Mode?

**Comment by JohnAZoidberg** [comment]
I put this commit into #1 to merge it faster and have less conflicts with my other branches.

**Comment by changab** [comment]
> Should we fail in `GetPeiServicesTablePointer` when we're in S-Mode?

Yes. We can't access to mscrach (PeiService pointer is saved here) CSR in S-mode. That makes sense to me we get fail in GetPeiServicesTablePointer in S-Mode. The good thing is we currently execute DXE in SMode,  and there is no code to use GetPeiServicesTablePointer.

**Pull request closed without merging**
